// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace schema
{

public enum POS : sbyte
{
  verb = 0,
  noun = 1,
  adj = 2,
  pronoun = 3,
  adv = 4,
  prep = 5,
  conj = 6,
  intj = 7,
  prefix = 8,
  suffix = 9,
  particle = 10,
  article = 11,
  unknown = 12,
};


}
